[package]
name = "sway-ast-stubs"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4.6"
num-traits = "0.2.16"
stacker = "0.1.16"
sway-ast = "0.68.2"
sway-features = "0.68.2"
sway-parse = "0.68.2"
sway-error = "0.68.2"
sway-types = "0.68.2"

[build-dependencies]
num-bigint = "0.4.3"
num-traits = "0.2.16"
proc-macro2 = "1.0.86"
quote = "1.0.37"
sway-ast = "0.68.2"
sway-features = "0.68.2"
sway-parse = "0.68.2"
sway-error = "0.68.2"
sway-types = "0.68.2"
